### ISSUE TITLE
Wrong genotype for reads with cluster size = 1

### ISSUE THREAD

**Issue by PhilippFW** [jweile/barseqPro#25]
Compliments on this nice package!

I have noticed that the genotype is erronously assigned as "=" when there is only 1 supporting CCS read.

I need those reads since I know the underlying Barcode-Variant association both from Sanger Sequencing of individual clones, which also agree with PacRAT variant call

Could you please fix this? When fixed, pacybara singificantly outperforms PacRAT in my hands: ca 770k vs 680k BC-variant associations

PS: I checked the "genoExtract.csv.gz" and the correct non-WT genotype is called there. Seems to be a bug?

**Comment by jweile** [comment]
Thanks for the kind words!

I suspect the problem is a result of the quality of the variant call being below the cutoff in the parameter file. If you check the Q-score listed in the `genoExtract.csv.gz` file (the number after the `:` symbol), and it is below the cutoff, it will not be carried forward into the final cluster genotype. If that's the case you could try lowering the cutoff (which may however result in more false-positives). 

Hope this helps. If not, let me know and I can take a closer look. 

Thanks!

**Comment by PhilippFW** [comment]
Indeed, the singleton handling was the issue. I relaxed the quality score in the parameters file and that solved the issue. Thanks!
